CREATE TABLE "users"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "phone_number" VARCHAR(255)  NOT NULL UNIQUE,
    "password"     VARCHAR(2048) NOT NULL,
    "user_name"    VARCHAR(255)  NOT NULL,
    "last_number"  VARCHAR(255)  NOT NULL,
    "coffee"       integer       NOT NULL DEFAULT '0',
    "coffee_happy" integer       NOT NULL DEFAULT '0',
    "active"       BOOLEAN       NOT NULL
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "user_role"
(
    "id"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint NOT NULL,
    "role_id" bigint NOT NULL
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "pay_day"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      bigint    NOT NULL,
    "active"       BOOLEAN   NOT NULL,
    "open_time"    timestamp NOT NULL,
    "close_time"   timestamp,
    "sum_all"      DECIMAL   NOT NULL DEFAULT '0.0',
    "sum_cash"     DECIMAL   NOT NULL DEFAULT '0.0',
    "sum_not_cash" DECIMAL   NOT NULL DEFAULT '0.0'
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "order"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pay_day_id" bigint    NOT NULL,
    "user_id"    bigint    NOT NULL,
    "time"       timestamp NOT NULL,
    "sum"        DECIMAL   NOT NULL DEFAULT '0.0',
    "is_cash"    BOOLEAN   NOT NULL
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "product"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category"     VARCHAR(255) NOT NULL,
    "product_name" VARCHAR(255) NOT NULL,
    "description"  VARCHAR(255),
    "is_dop"       BOOLEAN      NOT NULL
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "product_order"
(
    "id"               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id"         bigint NOT NULL,
    "product_price_id" bigint NOT NULL
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "size"
(
    "id"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "size_name" VARCHAR(255) NOT NULL
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "product_price"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" bigint  NOT NULL,
    "size_id"    bigint  NOT NULL,
    "price"      DECIMAL NOT NULL DEFAULT '0.0'
) WITH (
      OIDS= FALSE
    );



CREATE TABLE "role"
(
    "id"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR(255) NOT NULL
) WITH (
      OIDS= FALSE
    );



ALTER TABLE "user_role"
    ADD CONSTRAINT "user_role_fk0" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_role"
    ADD CONSTRAINT "user_role_fk1" FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "pay_day"
    ADD CONSTRAINT "pay_day_fk0" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order"
    ADD CONSTRAINT "order_fk0" FOREIGN KEY ("pay_day_id") REFERENCES "pay_day" ("id");
ALTER TABLE "order"
    ADD CONSTRAINT "order_fk1" FOREIGN KEY ("user_id") REFERENCES "users" ("id");


ALTER TABLE "product_order"
    ADD CONSTRAINT "product_order_fk0" FOREIGN KEY ("order_id") REFERENCES "order" ("id");
ALTER TABLE "product_order"
    ADD CONSTRAINT "product_order_fk1" FOREIGN KEY ("product_price_id") REFERENCES "product_price" ("id");


ALTER TABLE "product_price"
    ADD CONSTRAINT "product_price_fk0" FOREIGN KEY ("product_id") REFERENCES "product" ("id");
ALTER TABLE "product_price"
    ADD CONSTRAINT "product_price_fk1" FOREIGN KEY ("size_id") REFERENCES "size"("id");